# Docs: <https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/customizing-dependency-updates>

version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule: {interval: monthly}
    reviewers: [jacobalberty]
    assignees: [jacobalberty]

  - package-ecosystem: docker
    directory: /
    schedule: {interval: monthly}
    reviewers: [jacobalberty]
    assignees: [jacobalberty]
