services:
 - docker
install:
  - docker build -t unifi .
  - docker run -d -p 127.0.0.1:8443:8443 --name unifi unifi 
before_script:
  - sudo apt-get --yes --no-install-recommends install binfmt-support qemu-user-static
  - echo ':arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-arm-static:' | sudo tee -a /proc/sys/fs/binfmt_misc/register
script:
  - docker ps | grep -q unifi
